import fs from 'fs';
import path from 'path';

export class PluginManager {
  constructor(opencodeConfigPath, pluginPath) {
    this.opencodeConfigPath = path.resolve(opencodeConfigPath);
    this.pluginPath = path.resolve(pluginPath);
  }

  async status() {
    let enabled = false;
    let configValid = false;

    if (fs.existsSync(this.opencodeConfigPath)) {
      const config = JSON.parse(fs.readFileSync(this.opencodeConfigPath, 'utf-8'));
      const plugins = config.plugin || [];
      enabled = plugins.some(p => 
        typeof p === 'string' && p.includes('project-context-bootstrap')
      );
      configValid = true;
    }

    const pluginExists = fs.existsSync(this.pluginPath);

    return { enabled, pluginExists, configValid };
  }

  async enable() {
    const config = await this._readConfig();
    const pluginEntry = `file://${this.pluginPath}`;

    if (!config.plugin.includes(pluginEntry)) {
      config.plugin.push(pluginEntry);
      await this._writeConfig(config);
    }
    return true;
  }

  async disable() {
    const config = await this._readConfig();
    const pluginEntry = `file://${this.pluginPath}`;
    config.plugin = config.plugin.filter(p => p !== pluginEntry);
    await this._writeConfig(config);
    return true;
  }

  async createIfMissing() {
    if (fs.existsSync(this.pluginPath)) return true;

    const pluginDir = path.dirname(this.pluginPath);
    if (!fs.existsSync(pluginDir)) {
      fs.mkdirSync(pluginDir, { recursive: true });
    }

    const pluginCode = this._getPluginTemplate();
    fs.writeFileSync(this.pluginPath, pluginCode, 'utf-8');

    // Also add to config
    await this.enable();
    return true;
  }

  async ensureConfig() {
    const config = await this._readConfig();
    const pluginEntry = `file://${this.pluginPath}`;

    if (!config.plugin.includes(pluginEntry)) {
      config.plugin.push(pluginEntry);
      await this._writeConfig(config);
    }
    return true;
  }

  async _readConfig() {
    if (!fs.existsSync(this.opencodeConfigPath)) {
      return { plugin: [] };
    }
    try {
      return JSON.parse(fs.readFileSync(this.opencodeConfigPath, 'utf-8'));
    } catch {
      return { plugin: [] };
    }
  }

  async _writeConfig(config) {
    const existing = await this._readConfig();
    const merged = { ...existing, ...config };
    fs.writeFileSync(this.opencodeConfigPath, JSON.stringify(merged, null, 2), 'utf-8');
  }

  _getPluginTemplate() {
    return `/**
 * Universal Project Context Bootstrap Plugin
 * Auto-generated by memory-history skill
 */

const PROJECTS_ROOT = '/home/sunday/openidea/projects';

const TEMPLATES = {
  'AGENTS.md': \`# Project-Specific Agent Rules

This file defines agent behavior specific to this project. It extends the global AGENTS.md.

## Project-Specific Instructions

Add project-specific rules here. Examples:
- Coding conventions for this project
- Testing requirements
- Build/deploy commands
- Architecture decisions
- File organization patterns

## Instruction Priority (Global → Project)

1. User instructions (explicit requests)
2. **This file** (project AGENTS.md)
3. Project RULES.md
4. Global AGENTS.md
5. Skills

## Project-Specific Patterns

Document patterns unique to this codebase that agents should follow.
\`,

  'RULES.md': \`# Project Requirements & Constraints

This file documents project-specific requirements and constraints that must be followed.

## Requirements

List verified requirements here. Never invent requirements.

### Functional Requirements
- 

### Non-Functional Requirements
- 

## Constraints

Document hard constraints (technical, business, regulatory).

### Technical Constraints
- 

### Business Constraints
- 

### Regulatory/Compliance
- 

## Decisions

Record key technical decisions with rationale (ADR-style).
- 
\`,

  'PROJECT_CONTEXT.md': \`# Project Context

Stable project information. Only record verified information.

## Purpose

What problem does this project solve? Who is it for?

## Technology Stack

| Category | Technology | Version |
|----------|------------|---------|
| Language | | |
| Framework | | |
| Database | | |
| Build Tool | | |
| Test Framework | | |
| Package Manager | | |

## Architecture

Describe the high-level architecture (monolith, microservices, serverless, etc.)

### Key Components

| Component | Purpose | Location |
|-----------|---------|----------|
| | | |

## Repository Structure

\\\`\\\`\\\`text
project-root/
├── src/
│   ├── ...
├── tests/
├── docs/
└── ...
\\\`\\\`\\\`

## Important Files

| File | Purpose |
|------|---------|
| | |

## Dependencies

Key dependencies and their purposes.

## Commands

| Command | Purpose |
|---------|---------|
| \`dev\` | |
| \`build\` | |
| \`test\` | |
| \`lint\` | |
| \`typecheck\` | |

## Integrations

External services, APIs, third-party tools.

## Configuration

Environment variables, config files, secrets management.

## Deployment

Deployment targets, pipelines, environments.

## Stable Technical Decisions

Decisions that are unlikely to change. Reference ADRs if applicable.
\`,

  'SESSION_HANDOFF.md': \`# Session Handoff

Current project/session state for continuity across sessions.

## Objective

What is the current goal or task?

## Completed Work

- 

## Changed Files

| File | Change |
|------|--------|
| | |

## Current State

Describe the current state of the work.

## Verification

What has been verified? What tests pass?

## Decisions

Key decisions made in this session.

## Known Issues

Any known problems or blockers.

## Unfinished Work

What remains to be done?

## Investigations Completed

What has been investigated and resolved.

## Exact Next Steps

1. 
2. 
3. 
\`
};

function isUnderProjectsRoot(dir) {
  const resolved = dir.replace(/\\/+$/, '');
  const root = PROJECTS_ROOT.replace(/\\/+$/, '');
  return resolved === root || resolved.startsWith(root + '/');
}

function getProjectName(dir) {
  const root = PROJECTS_ROOT.replace(/\\/+$/, '');
  const relative = dir.replace(root + '/', '');
  return relative.split('/')[0];
}

async function readFileSafe(\$, filePath) {
  try {
    const result = await \$\`cat \${filePath}\`.quiet().text();
    return result;
  } catch {
    return null;
  }
}

async function writeFile(\$, filePath, content) {
  await \$\`printf '%s\\\\n' "\${content.replace(/%/g, '%%').replace(/\\\\/g, '\\\\\\\\').replace(/\\n/g, '\\\\n')}" > \${filePath}\`.quiet();
}

async function writeFileIfMissing(\$, filePath, content) {
  const existing = await readFileSafe(\$, filePath);
  if (existing === null) {
    await writeFile(\$, filePath, content);
    return 'created';
  }
  const trimmed = existing.trim();
  if (trimmed === '') {
    await writeFile(\$, filePath, content);
    return 'updated';
  }
  return 'preserved';
}

async function ensureProjectContext(\$, projectDir) {
  const results = {};
  for (const [fileName, template] of Object.entries(TEMPLATES)) {
    const filePath = \`\${projectDir}/\${fileName}\`;
    results[fileName] = await writeFileIfMissing(\$, filePath, template);
  }
  return results;
}

async function bootstrapProjectContext({ \$, directory }) {
  if (!isUnderProjectsRoot(directory)) {
    return { skipped: true, reason: 'Not under projects root' };
  }

  const projectName = getProjectName(directory);
  const projectDir = \`\${PROJECTS_ROOT}/\${projectName}\`;
  const actualProjectDir = directory.startsWith(projectDir + '/') ? projectDir : directory;

  const results = await ensureProjectContext(\$, actualProjectDir);
  return { project: projectName, projectDir: actualProjectDir, files: results };
}

export default async function ProjectContextBootstrap({ \$, directory, project, client }) {
  await bootstrapProjectContext({ \$, directory });

  return {
    event: async ({ event }) => {
      if (event.type === 'session.created') {
        const sessionDir = event.properties?.info?.directory || directory;
        await bootstrapProjectContext({ \$, directory: sessionDir });
      }
      if (event.type === 'session.idle') {
        const sessionDir = event.properties?.info?.directory || directory;
        if (isUnderProjectsRoot(sessionDir)) {
          const projectName = getProjectName(sessionDir);
          const projectDir = \`\${PROJECTS_ROOT}/\${projectName}\`;
          await updateSessionHandoff(\$, projectDir, {
            currentState: 'Session completed',
            verification: 'Session ended naturally',
            nextSteps: ['Resume from last session state']
          });
        }
      }
      if (event.type === 'session.next.compaction.ended') {
        const sessionDir = event.properties?.info?.directory || directory;
        if (isUnderProjectsRoot(sessionDir)) {
          const projectName = getProjectName(sessionDir);
          const projectDir = \`\${PROJECTS_ROOT}/\${projectName}\`;
          await updateSessionHandoff(\$, projectDir, {
            currentState: 'Session compacted — summary preserved',
            verification: \`Compaction reason: \${event.properties?.reason || 'auto'}\`,
            nextSteps: ['Resume work from last checkpoint']
          });
        }
      }
    },
    "experimental.session.compacting": async (input, output) => {
      if (isUnderProjectsRoot(directory)) {
        const projectName = getProjectName(directory);
        const projectDir = \`\${PROJECTS_ROOT}/\${projectName}\`;
        const handoff = await readFileSafe(\$, \`\${projectDir}/SESSION_HANDOFF.md\`);
        if (handoff) {
          output.context = output.context || [];
          output.context.push(\`
## Project Session Context (from SESSION_HANDOFF.md)
Project: \${projectName}
Directory: \${projectDir}

\${handoff.slice(0, 3000)}
\`);
        }
      }
    },
    config: async () => {
      await bootstrapProjectContext({ \$, directory });
    }
  };
}

async function updateSessionHandoff(\$, projectDir, info) {
  const handoffPath = \`\${projectDir}/SESSION_HANDOFF.md\`;
  const existing = await readFileSafe(\$, handoffPath);
  if (!existing) return 'not-found';

  const now = new Date().toISOString().split('T')[0];
  const time = new Date().toISOString().split('T')[1].slice(0, 8);
  let updateEntry = \`\n## Session Update — \${now} \${time}\n\n\`;

  if (info.currentState) updateEntry += \`**Current State:** \${info.currentState}\n\n\`;
  if (info.verification) updateEntry += \`**Verification:** \${info.verification}\n\n\`;
  if (info.nextSteps?.length) {
    updateEntry += \`**Exact Next Steps:**\n\`;
    for (let i = 0; i < info.nextSteps.length; i++) updateEntry += \`\${i + 1}. \${info.nextSteps[i]}\n\`;
    updateEntry += '\n';
  }

  const insertMarker = '## Exact Next Steps';
  const idx = existing.lastIndexOf(insertMarker);
  let updated;
  if (idx >= 0) {
    const afterMarker = existing.indexOf('\n\n', idx);
    if (afterMarker >= 0) {
      updated = existing.slice(0, afterMarker + 2) + updateEntry + existing.slice(afterMarker + 2);
    } else {
      updated = existing + updateEntry;
    }
  } else {
    updated = existing + updateEntry;
  }
  await writeFile(\$, handoffPath, updated);
  return 'updated';
}
`;
  }
}